### ISSUE TITLE
pdf-tools: fails during installation 

### ISSUE THREAD

**Issue by foundjem** [Homebrew/homebrew-emacs#757]
/usr/local/Homebrew/Library/Homebrew/utils/github.rb:258:in `raise_api_error': Validation Failed: [{"message"=>"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.", "resource"=>"Search", "field"=>"q", "code"=>"invalid"}] (GitHub::ValidationFailedError)
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:212:in `open_api'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:357:in `search'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:265:in `search_issues'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:278:in `issues_for_formula'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:375:in `fetch_issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:371:in `issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:425:in `dump'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:141:in `rescue in <main>'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:38:in `<main>'

**Comment by ndw** [comment]
Ditto me on Catalina.

I wonder if the preceding error is also significant:

```
==> make server/epdfinfo CC=/usr/bin/gcc CXX=/usr/bin/gcc AR=/usr/bin/ar RANLIB=/usr/bin/ranlib
Last 15 lines from /Users/ndw/Library/Logs/Homebrew/pdf-tools/01.make:
                          ~  ^
poppler-hack.cc:88:16: error: cannot initialize a variable of type 'GooString *' with an rvalue of type 'const GooString *'
    GooString *state = a->annot->getAppearState ();
               ^       ~~~~~~~~~~~~~~~~~~~~~~~~~~~
poppler-hack.cc:108:19: error: assigning to 'GooString *' from incompatible type 'const GooString *'
    text = annot->getDate ();
           ~~~~~~~^~~~~~~~~~
3 errors generated.
make[2]: *** [epdfinfo-poppler-hack.o] Error 1

```

**Comment by dunn** [comment]
Looks like the same error as https://github.com/politza/pdf-tools/issues/389

**Comment by ndw** [comment]
Looks like, but...

```
gmake[2]: Entering directory '/private/tmp/x/pdf-tools-0.80/server'
/usr/bin/gcc -DHAVE_CONFIG_H -I.    -Wall -Wall -I/usr/local/include -I/usr/local/Cellar/glib/2.62.4/include/glib-2.0 -I/usr/local/Cellar/glib/2.62.4/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/libffi/3.2.1/lib/libffi-3.2.1/include -I/usr/local/include -I/usr/local/Cellar/poppler/0.84.0/include/poppler/glib -I/usr/local/Cellar/poppler/0.84.0/include/poppler -I/usr/local/Cellar/cairo/1.16.0_2/include/cairo -I/usr/local/Cellar/glib/2.62.4/include -I/usr/local/Cellar/glib/2.62.4/include/glib-2.0 -I/usr/local/Cellar/glib/2.62.4/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pixman/0.38.4/include/pixman-1 -I/usr/local/Cellar/fontconfig/2.13.1/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/libpng/1.6.37/include/libpng16 -I/usr/local/Cellar/poppler/0.84.0/include/poppler -I/usr/local/Cellar/libpng/1.6.37/include/libpng16 -std=c++11 -g -O2 -MT epdfinfo-poppler-hack.o -MD -MP -MF .deps/epdfinfo-poppler-hack.Tpo -c -o epdfinfo-poppler-hack.o `test -f 'poppler-hack.cc' || echo './'`poppler-hack.cc
poppler-hack.cc:62:30: error: no member named 'getCString' in 'GooString'
      result = g_convert (s->getCString () + 2,
```
